name: Unit Tests on Ubuntu

on:
  push:
    branches:
      - main
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  unit_test:
    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Clone Main Repository
      uses: actions/checkout@v4

    - name: Create Build Environment
      shell: bash
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: >
        cmake ${GITHUB_WORKSPACE}
        -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
        -DCPP_UTILITY_BUILD_TESTS=ON

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel --config ${BUILD_TYPE}

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${BUILD_TYPE} --output-on-failure
